### ISSUE TITLE
ciao, mi interessa molto questo contributo che hai sviluppato, è un paio di giorni che provo a collegare una centrale ksenia , ma senza aver nessun successo.

### ISSUE THREAD

**Issue by alessandro52net** [Supergiovane/node-red-contrib-sia-ultimate#1]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Knx-Ultimate Version**
 - Eg. 1.1.95

**Are you running node-red behind homematic, docker or anything similar?**
 - Eg. Node-Red running alone in RaspberryPi

**Additional context**

**Comment by alessandro52net** [comment]
![image](https://user-images.githubusercontent.com/62192639/142210090-2db18384-f352-472b-936d-c75b082d4dc1.png)
questa e la configurazione lato centrale
![image](https://user-images.githubusercontent.com/62192639/142210547-26f3dd2c-92ab-496f-aee2-e136cec45447.png)
questa e lato nodered

**Comment by Supergiovane** [comment]
Ciao
Per prima cosa dovresti assicurarti che la porta 1026 sia aperta sul PC su cui gira node-red.
Per il resto, mi sa che occorre che lo ksenia monitori la connessione con il node, per cui io abiliterei "modalità supervisione", secondo me. Però non sono sicuro che sia quella l'opzione corretta.
Dovresti magari sentire sul gruppo facebook di ksenia, perchè io ho provato solo con AJAX.

**Comment by alessandro52net** [comment]
ciao.
 mi sa che hai ragione la porta 1026 non è aperta ,sapresti come si aprono le porte su raspberry p4 model b con debiam installato? o mi consigli un'alternativa di porta da utilizzare?
![image](https://user-images.githubusercontent.com/62192639/142268128-4686286b-5879-4611-b504-4e9843e4783f.png)

**Comment by Supergiovane** [comment]
Ciao
No, se non hai praticità con debian, dovresti guardate su internet. Magari guarda su qualche forum raspbian.

**Comment by alessandro52net** [comment]
avevi ragione la porta non era aperta, cambiato porta e comunica con ksenia.
