### ISSUE TITLE
Nde red

### ISSUE THREAD

**Issue by Syssicreation** [Supergiovane/node-red-contrib-sia-ultimate#12]
Hello I am interested in your code
I have an ajax alarm
I would like to retrieve the states of the ajax elements on a web page
Your work is interesting but I know nothing about node red
is it possible to make a tutorial to install the sia server on node red that I installed on a raspbery pi
Thank you very much

**Comment by Supergiovane** [comment]
Hi
You should ask on the node red forum, or search online. There are a lot of tutorials. I can only help you if there is a bug on the node ;-)
