### ISSUE TITLE
Cannot read property 'address' of null

### ISSUE THREAD

**Issue by calania** [Supergiovane/node-red-contrib-sia-ultimate#3]
Hello! I just installed this node but can't get it working. My node red crashes after I installed it and I am getting the following error. Do you have any idea what could be causing this? I am using the latest version.

```
28 Dec 11:03:22 - [info] siaendpointConfig: siaendpointConfig: Account: 000, AES:false, HEX:false
28 Dec 11:03:22 - [info] siaendpointConfig: siaendpointConfig: Total SIA codes in csv file: 280
28 Dec 11:03:22 - [info] siaendpointConfig: siaendpointConfig: Account: undefined, AES:false, HEX:false
28 Dec 11:03:22 - [info] siaendpointConfig: siaendpointConfig: Total SIA codes in csv file: 280
28 Dec 11:03:23 - [info] Started flows
28 Dec 11:03:23 - [red] Uncaught Exception:
28 Dec 11:03:23 - TypeError: Cannot read property 'address' of null
    at Server.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-sia-ultimate/nodes/siaendpoint-config.js:402:112)
    at Object.onceWrapper (events.js:299:28)
    at Server.emit (events.js:210:5)
    at emitListeningNT (net.js:1335:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.

```

**Comment by Supergiovane** [comment]
Hi
do you have correctly set the options ? Please check if there are spaces.

**Comment by Supergiovane** [comment]
Please also post a screenshot of your config window. Thanks.

**Comment by calania** [comment]
The problem is that  node red dosen't start now so I can't access the gui config to change the address. But I can properly change it in the file that the settings is stored in. Where is it stored on the pi?

**Comment by Supergiovane** [comment]
...wait a sec...

**Comment by calania** [comment]
I know that I am using a older version of node red. Do you think that could be a issue?

**Comment by Supergiovane** [comment]
Yes, you should update node-red and node.js as well. It's always a good idea.
Let's take a look why it crashes.
Please unzip this file into your **./node-red/node_modules/node-red-contrib-sia-ultimate/nodes** folder and restart node-red

[siaendpoint-config.js.zip](https://github.com/Supergiovane/node-red-contrib-sia-ultimate/files/7784133/siaendpoint-config.js.zip)

**Comment by Supergiovane** [comment]
V 1.0.3 is out with fix for the crash, but you need to see the log and understand what happen. Maybe an already used port?

**Comment by calania** [comment]
It seems like I am sadly getting the same error whive the file you provided havent tried 1.0.3 yet. (however the line changed in the error). Thanks for the super quick help but I need to go right now. Will look at it tonight!


```
28 Dec 11:29:10 - [info] siaendpointConfig: siaendpointConfig: Account: 000, AES:false, HEX:false
28 Dec 11:29:10 - [info] siaendpointConfig: siaendpointConfig: Total SIA codes in csv file: 280
28 Dec 11:29:10 - [info] siaendpointConfig: siaendpointConfig: Account: undefined, AES:false, HEX:false
28 Dec 11:29:10 - [info] siaendpointConfig: siaendpointConfig: Total SIA codes in csv file: 280
28 Dec 11:29:11 - [info] Started flows
28 Dec 11:29:11 - [red] Uncaught Exception:
28 Dec 11:29:11 - TypeError: Cannot read property 'address' of null
    at Server.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-sia-ultimate/nodes/siaendpoint-config.js:403:116)
    at Object.onceWrapper (events.js:299:28)
    at Server.emit (events.js:210:5)
    at emitListeningNT (net.js:1335:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
```

**Comment by Supergiovane** [comment]
Hi
Sure? Have you restarted node-red? Be sure to overwrite the existing file.
you may have the port alreasy used by someone else.
The node fails to instantiate the TCP server. The new version take care of that avoiding crash.

**Comment by Supergiovane** [comment]
V. 1.0.4 is also out with more logs..

**Comment by calania** [comment]
I can't look at it right now but if I want to update it should I then run "npm unistall" first and then "npm install" (with the name of the node) in the. /node-red folder to update the node?

**Comment by Supergiovane** [comment]
Nope.
Just install the update when you see it in the Palette Menu of node-red.

<img width="463" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/147558887-02245a73-7606-4e05-9ff8-c70c4ff76738.png">

Doesn't install nothing by hand!

**Comment by calania** [comment]
But the problem is that node red doesn't start. It is in a infinite boot loop so I can't access the pallette menu.

**Comment by Supergiovane** [comment]
Ah, ok, sorry.
Please cd into **. /node-red** and npm uninstall node-red-contrib-sia-ultimate.

**Comment by calania** [comment]
I have made a little progress. I installed the newest version and am now getting the following error.

```
28 Dec 13:06:40 - [info] Starting flows
28 Dec 13:06:40 - [info] siaendpointConfig: siaendpointConfig: Account: 000, AES:false, HEX:false
28 Dec 13:06:40 - [info] siaendpointConfig: siaendpointConfig: Total SIA codes in csv file: 280
28 Dec 13:06:40 - [info] siaendpointConfig: siaendpointConfig: Account: undefined, AES:false, HEX:false
28 Dec 13:06:40 - [info] siaendpointConfig: siaendpointConfig: Total SIA codes in csv file: 280
28 Dec 13:06:42 - [info] Started flows
28 Dec 13:06:42 - [info] [mqtt-broker:Raspberry] Connected to broker: mqtt://192.168.0.214:1883
28 Dec 13:06:45 - [info] siaendpointConfig: SIA Server listening on IP-Adress (TCP): ::
28 Dec 13:06:45 - [info] siaendpointConfig: SIA Server listening on IP-Adress (UDP): 0.0.0.0:4628
28 Dec 13:06:45 - [red] Uncaught Exception:
28 Dec 13:06:45 - Error: listen EADDRINUSE: address already in use :::4628
    at Server.setupListenHandle [as _listen2] (net.js:1301:14)
    at listenInCluster (net.js:1349:12)
    at Server.listen (net.js:1437:7)
    at serverStartTCP (/home/pi/.node-red/node_modules/node-red-contrib-sia-ultimate/nodes/siaendpoint-config.js:402:27)
    at Timeout._onTimeout (/home/pi/.node-red/node_modules/node-red-contrib-sia-ultimate/nodes/siaendpoint-config.js:832:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 14.
Stopped Node-RED graphical event wiring tool.
```

I am however able to access node red for a few seconds before it reboots and if I look in the node it seems like I have accidentally created two server users (both using the same port) and the one that is selected doesn't have a SIA ACCOUNT

This is the server that is selected for the node:
<img width="693" alt="Screenshot 2021-12-28 at 13 33 58" src="https://user-images.githubusercontent.com/34073343/147566706-ac0d000c-2e03-4f3a-87de-d9fb47a23bc9.png">

And this is the other server that is not selected
<img width="573" alt="Screenshot 2021-12-28 at 13 33 15" src="https://user-images.githubusercontent.com/34073343/147566658-7fc79607-92aa-4083-a74b-f6e18a08be84.png">

However node red restarts before I am able to remove the server without a account and deploy the change meaning that I am still stuck in a boot loop and can't remove the broken server.

**Comment by Supergiovane** [comment]
That's weird that it reboots.
Have you installed the v.1.0.4?

**Comment by Supergiovane** [comment]
Ok, anyway.... i'm able to reproduce the issue.... wait a sec, i'll fix that...

**Comment by calania** [comment]
Yes I have. However I just managed to fix it. I was able to remove the old server and then spam click the deploy button so that node red deployed the changes before it had time to restart. It seems to be working now. Thanks for the help!

**Comment by Supergiovane** [comment]
Good, but i'm still working on a fix, to avoid future issues.

**Comment by calania** [comment]
Sounds good! I had a look at the node red pallete now that everything works and it says that version 1.0.4 is installed so it seems like your fix didn't work

**Comment by Supergiovane** [comment]
V. 1.0.5 is out with the final fix.
Please install it as soon as you see it.
Thanks for opening the issue!

**Comment by calania** [comment]
Thanks to you for being so helpful :)

**Comment by EmilionDK** [comment]
@Supergiovane Hey :) 
After I updated it to 1.0.5 it can't run at on my server more.

4 Jan 09:26:22 - [error] siaendpointConfig: Unable to instantiate the TCP server: Cannot read property 'remoteAddress' of undefined do you have another config node with the same port?

If I manually install older versions it works. :)

![SABf8Yp3pT](https://user-images.githubusercontent.com/17970519/148035035-e5562536-52fa-4979-a492-aa171a11b636.png)
