### ISSUE TITLE
After update to 1.0.5 "Cannot read property"

### ISSUE THREAD

**Issue by EmilionDK** [Supergiovane/node-red-contrib-sia-ultimate#4]
Hey :) 
After I updated it to 1.0.5 it can't run at on my server more.

4 Jan 09:26:22 - [error] siaendpointConfig: Unable to instantiate the TCP server: Cannot read property 'remoteAddress' of undefined do you have another config node with the same port?

If I manually install older versions it works. :)

![SABf8Yp3pT](https://user-images.githubusercontent.com/17970519/148035035-e5562536-52fa-4979-a492-aa171a11b636.png)

**Comment by Supergiovane** [comment]
Hi
please stay with the older version.
I'm working on TTS-Ultimate node now. As soon as finished, i'll return to you.

**Comment by EmilionDK** [comment]
> Hi please stay with the older version. I'm working on TTS-Ultimate node now. As soon as finished, i'll return to you.

No problem, and again thank you very much for your work!
I'm throwing a donation your way :)

**Comment by Supergiovane** [comment]
Thank you!! Appreciate that!!

**Comment by Supergiovane** [comment]
Hi
can you show me your config window? Are you sure not to have two server nodes with the same port?

**Comment by EmilionDK** [comment]
> Hi can you show me your config window? Are you sure not to have two server nodes with the same port?

200% sure i only have one node. it happens on 2 different server in 2 locations in and both places it happens after updating. :)

**Comment by Supergiovane** [comment]
Ok tomorrow i’ll look at that!

**Comment by EmilionDK** [comment]
> Ok tomorrow i’ll look at that!

Just take your time, right now I'm using the other version. 1.0.4 :D

**Comment by Supergiovane** [comment]
Hi
i'm able to reproduce the issue. A fix will be out in about 1 hour.

**Comment by Supergiovane** [comment]
Hi
please unzip the attached file into your **.node-red/node_modules/node-red-contrib-sia-ultimate/nodes** folder and restart node-red
Le me know if it fixed your issue.
Thanks
[siaendpoint-config.js.zip](https://github.com/Supergiovane/node-red-contrib-sia-ultimate/files/7812941/siaendpoint-config.js.zip)
.

**Comment by EmilionDK** [comment]
Hey @Supergiovane 

I have now tested it and it works as it should again. :)

**Comment by Supergiovane** [comment]
Good
Update to the latest.
