### ISSUE TITLE
Nodered crash

### ISSUE THREAD

**Issue by bolfox** [Supergiovane/node-red-contrib-sia-ultimate#5]
Hi Max,

i have installed you sia on my nodered docker on synolgy where is running also knx ultimate.
Last week on first try after the node deployment, nodered was crashing instantly.
This evening i'm trying again:
before i was using port 96, this evening port 4626 and it was NOT crashing....

BUT

it won't connect

I'm on nodered 3.0.2
I have disabled the firewall
I'm on HUB 2 (4G) with fw 2.16.1

**Comment by bolfox** [comment]
Ok, probably found the problem...
It seem that the port is locked by the docker, now i forced it and it seem to work.
I will test it and repost back on next days...

Sorry for the inconvenience...

**Comment by Supergiovane** [comment]
Hi
it's useful to see the log when node-red crashes, because it should'nt crash, even if the port is wrong.
