### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by mrc1973** [Supergiovane/node-red-contrib-sia-ultimate#7]
Node red crashes when you try to add a new site with the same port, is this using the latest port of the iobroker.sia plugin?

Just to confirm it is acting as a SIA server where multiple accounts (panels) can be added and filtered by its sia account number?

**Comment by Supergiovane** [comment]
Hi
There is a port conflict.
SIA Ultimate is meant to receive the SIA messages sent by an alarm panel. You cannot start several servers on the same port.
Yes, you must use SIA account to distinguish between clients.

**Comment by mrc1973** [comment]
ok when i add a new account it still crashes, this is not present in the iobroker version as it listens on 1 port and accounts are set up separately and filtered by its sia account, all on the same port, this is why i asked if its based on the latest version of the iobroker.sia plugin?

**Comment by Supergiovane** [comment]
Hi
I don't use iobroker, so i cannot help in that, but as i told you, you cannot have more than 1 application listening on the same port.
About the crash, i'll take a look today and i'll release a new version to fix the issue.

**Comment by mrc1973** [comment]
yes i am aware there is no way to run more than one instance, but the 1 instance that is running should handle multiple panels via the sia account which filters sia codes from more than one alarm panel. thank you for looking into this. :-)

**Comment by Supergiovane** [comment]
node-red-contrib-sia-ultimate@1.0.9 is out with the crash fixed.
