### ISSUE TITLE
error: write after end

### ISSUE THREAD

**Issue by goran-mahovlic** [Supergiovane/node-red-contrib-sia-ultimate#8]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

HI, thank you on this great plugin! It looks super useful but I still did not get it to run.

**Describe the bug**

In debug window of node-red I am just getting this error

"siaendpointConfig: TCP Connection ::ffff:myip:port error: write after end"

**Expected behavior**
I am hoping to receive messages

**Knx-Ultimate Version**
 Version 1.0.9

**Are you running node-red behind homematic, docker or anything similar?**
 node red is running on Ubuntu that is on digitalocean

**Comment by Supergiovane** [comment]
Hi
Can you show me the configuration window of sia node?

**Comment by goran-mahovlic** [comment]
> Hi Can you show me the configuration window of sia node?

Hi, thank you for replaying, and sorry for late answer I have tried all night to update server to get it working but for now nothing helped 

Here are screens - it is visible that some traffic is generated but for some reason it does not connect

![Screenshot from 2024-05-05 12-16-25](https://github.com/Supergiovane/node-red-contrib-sia-ultimate/assets/4248736/125379d5-8912-4755-976f-a7e007bd41e7)

![Screenshot from 2024-05-05 12-16-43](https://github.com/Supergiovane/node-red-contrib-sia-ultimate/assets/4248736/b30e1517-73a0-49dd-a329-d0d4d513dd95)

**Comment by Supergiovane** [comment]
Hi
the error **"4628 error: write after end"** means that the alarm is connected, but for some reasons, the payload sent by the alarm cannot match the length expected by the node.
Other than that, "::ffff:104.248" is a IPv6 address. Are you sure about that? Is your alarm system using IPv6?
Are you sure that the SIA Account "radiona" is correct? Usually, this is a number only field.
Thanks.

**Comment by goran-mahovlic** [comment]
Thank you!
I did not understandthat  SIA Account needs to be that number - now I got it to receive data from first location!

What would be best way to add next location, as I have two - should I just use same port and settings just change SIA account - or I need to se different port?

**Comment by Supergiovane** [comment]
Hi
You must change the port as well. It's not allowed to have more than one socket on the same port.
Happy that it wokks now!

**Comment by goran-mahovlic** [comment]
Got it! I am now receiving messages from both alarms! 

Thank you for your work!

Your other projects also looks great, next I will need to try to get events for camera.

My use case is that is there is no one in rooms for some time and alarm is not ON - we need to react - so I will send mail to group that someone need to check cameras and arm system is there is no one in place...

I will close this issue.

**Comment by Supergiovane** [comment]
You're wellcome!!
